#!/usr/bin/env bash
# Write a Bash script that displays:
#     To infinity and beyond indefinitely
#     With a sleep 2 in between each iteration
#     I am invincible!!! when receiving a SIGTERM signal

# Defne sigterm handler function
function sigterm_handler {
    echo "I am invincible!!!"
    exit 1
}
# Set up the trap
trap sigterm_handler SIGTERM SIGINT

while true; do 
    echo "To infinity and beyond"
    sleep 2
done