#!/usr/bin/env bash
# Write a Bash script that displays numbers from 1 to 100.
# 	Displays "FizzBuzz" when the number is a multiple of 3 and 5
# 	Displays "Fizz" when the number is multiple of 3
# 	Displays "Buzz" when the number is a multiple of 5
# 	Otherwise, displays the number
# 	In a list format

var1=0
while [ $var1 -lt 100 ] 
do
	var1=$((var1 + 1))
	if [ $((var1%3)) -eq 0 ]
	then
		if [ $((var1%5)) -eq 0 ]
		then
			echo "FizzBuzz"
		else
			echo "Fizz"
		fi
	elif [ $((var1%5)) -eq 0 ]
	then
		echo "Buzz"
	else
		echo "$var1"
	fi
done
