#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
# but for the 9th iteration, displays Best School and then "Hi" on a new line.
str="Best School"
var1=0
while [ $var1 -lt 10 ]
do
	echo "$str"
	var1=$((var1 + 1))
	if [ $var1 -eq 9 ]
	then
		echo "Hi"
	fi
done
