#!/usr/bin/env bash
# Write a Bash script that displays the time for 12 hours and 59 minutes:
# 	display hours from 0 to 12
# 	display minutes from 1 to 59
# You must use the while loop (for and until are forbidden)

var1=-1
var2=0
while [ $var1 -lt 12 ]
do
	var1=$((var1 + 1))
	echo "Hour: $var1"
	while [ $var2 -lt 59 ]
	do
		var2=$((var2 + 1))
		echo "$var2"
	done
	var2=0
done
