#!/usr/bin/env bash
# Getting `Apache` running on the container and return a page
# containing `Hello Holberton` when querying the root of it.
sudo apt update -y
sudo apt install -y apache2
sudo echo "Hello Holberton" > /var/www/html/index.html
sudo service apache2 start
sudo systemctl enable apache2
